# Generated by Django 4.1.7 on 2023-02-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=1000)),
                ("num_rows", models.IntegerField(blank=True)),
                ("num_cols", models.IntegerField(blank=True)),
                (
                    "column_wise_distinct_values",
                    models.JSONField(blank=True, default=dict),
                ),
                ("column_wise_null_values", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
